/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtFloat: typeof import('./src/components/arts/ArtFloat.vue')['default']
    ListPhotos: typeof import('./src/components/lists/ListPhotos.vue')['default']
    ListPosts: typeof import('./src/components/lists/ListPosts.vue')['default']
    NavBar: typeof import('./src/components/core/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./src/components/core/ToggleTheme.vue')['default']
    WrapperPost: typeof import('./src/components/wappers/WrapperPost.vue')['default']
  }
}
