/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArkBanner: typeof import('./src/components/core/ArkBanner.vue')['default']
    NavBar: typeof import('./src/components/core/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WapperPost: typeof import('./src/components/WapperPost.vue')['default']
    WrapperPhoto: typeof import('./src/components/wappers/WrapperPhoto.vue')['default']
    WrapperPost: typeof import('./src/components/wappers/WrapperPost.vue')['default']
  }
}
